USE movies;

-- Exercise 1
SELECT TITLE, YEAR
FROM MOVIE
WHERE 
    CASE 
        WHEN LENGTH IS NULL THEN 1
        WHEN LENGTH > 120 AND YEAR < 2000 THEN 1
        ELSE 0
    END = 1;

-- Exercise 2
SELECT NAME, GENDER
FROM MOVIESTAR
WHERE NAME LIKE 'J%' AND BIRTHDATE>1948
ORDER BY NAME DESC;

-- Exercise 3
SELECT s.NAME AS StudioName, COUNT(DISTINCT si.STARNAME) AS ActorCount
FROM STUDIO s
LEFT JOIN MOVIE m ON m.STUDIONAME = s.NAME
LEFT JOIN STARSIN si ON si.MOVIETITLE = m.TITLE
GROUP BY s.NAME
ORDER BY s.NAME;

-- Exercise 4
SELECT si.STARNAME AS 'Actor Name', COUNT(m.TITLE) AS 'No. movies'
FROM STARSIN AS si
LEFT JOIN MOVIE AS m ON si.MOVIETITLE=m.TITLE
GROUP BY si.STARNAME
ORDER BY si.STARNAME ASC;

-- Exercise 5
SELECT s.NAME AS StudioName, m.TITLE AS MovieTitle
FROM STUDIO s
LEFT JOIN MOVIE m ON s.NAME = m.STUDIONAME
WHERE m.YEAR = (SELECT MAX(m1.YEAR) FROM MOVIE m1 WHERE m1.STUDIONAME = s.NAME)
ORDER BY s.NAME ASC;

-- Exercise 6
SELECT NAME, BIRTHDATE
FROM MOVIESTAR
WHERE BIRTHDATE >= ALL (SELECT BIRTHDATE FROM MOVIESTAR) AND GENDER='M';

-- Exercise 7
